"""Initial config tables

Revision ID: 1b101599d8d8
Revises: 
Create Date: 2026-03-10 23:22:04.785891
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b101599d8d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consumer_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_storage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('BATTERY', 'HEAT', 'COLD', name='storagetype'), nullable=False),
    sa.Column('capacity_kwh', sa.Float(), nullable=False),
    sa.Column('max_charge_kw', sa.Float(), nullable=False),
    sa.Column('max_discharge_kw', sa.Float(), nullable=False),
    sa.Column('soc_min_pct', sa.Float(), nullable=False),
    sa.Column('soc_max_pct', sa.Float(), nullable=False),
    sa.Column('soc_pct', sa.Float(), nullable=False),
    sa.Column('current_power_kw', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('forecast_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('forecast_type', sa.String(length=50), nullable=False),
    sa.Column('value_kw', sa.Float(), nullable=False),
    sa.Column('confidence_lower_kw', sa.Float(), nullable=True),
    sa.Column('confidence_upper_kw', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forecasts_forecast_time'), ['forecast_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_forecasts_forecast_type'), ['forecast_type'], unique=False)

    op.create_table('generator_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('PV', 'HEAT_PUMP', 'CHP', 'BOILER', 'CHILLER', name='generatortype'), nullable=False),
    sa.Column('energy_form', sa.Enum('ELECTRICITY', 'HEAT', 'COLD', name='energyform'), nullable=False),
    sa.Column('max_power_kw', sa.Float(), nullable=False),
    sa.Column('min_power_kw', sa.Float(), nullable=False),
    sa.Column('efficiency', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_controllable', sa.Boolean(), nullable=False),
    sa.Column('current_power_kw', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_measurements_metric'), ['metric'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_timestamp'), ['timestamp'], unique=False)

    op.create_table('meter_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storage_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wallboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('max_power_kw', sa.Float(), nullable=False),
    sa.Column('min_power_kw', sa.Float(), nullable=False),
    sa.Column('phases', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('connector_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charging_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallbox_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.Enum('MAX_SPEED', 'PV_SURPLUS', 'TARGET_CHARGE', name='chargingmode'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CHARGING', 'PAUSED', 'COMPLETED', 'CANCELLED', name='sessionstatus'), nullable=False),
    sa.Column('current_power_kw', sa.Float(), nullable=False),
    sa.Column('energy_charged_kwh', sa.Float(), nullable=False),
    sa.Column('vehicle_battery_capacity_kwh', sa.Float(), nullable=True),
    sa.Column('vehicle_soc_pct', sa.Float(), nullable=True),
    sa.Column('vehicle_efficiency_kwh_per_km', sa.Float(), nullable=False),
    sa.Column('target_km', sa.Float(), nullable=True),
    sa.Column('target_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('target_energy_kwh', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['wallbox_id'], ['wallboxes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('charging_sessions')
    op.drop_table('wallboxes')
    op.drop_table('system_settings')
    op.drop_table('storage_configs')
    op.drop_table('room_configs')
    op.drop_table('meter_configs')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_timestamp'))
        batch_op.drop_index(batch_op.f('ix_measurements_source'))
        batch_op.drop_index(batch_op.f('ix_measurements_metric'))

    op.drop_table('measurements')
    op.drop_table('generators')
    op.drop_table('generator_configs')
    with op.batch_alter_table('forecasts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forecasts_forecast_type'))
        batch_op.drop_index(batch_op.f('ix_forecasts_forecast_time'))

    op.drop_table('forecasts')
    op.drop_table('energy_storage')
    op.drop_table('consumer_configs')
    op.drop_table('circuit_configs')
    # ### end Alembic commands ###
